package com.shawn.newrollcall.Intentcenter.action;

/**
 * Created by Shawn Wu on 2017/11/30.
 *
 */

public interface IntentCenterActionsType {

    String INTENT_MAIN_ACTIVITY = "INTENT_MAIN_ACTIVITY";
    String BACK_TO_LOGIN = "BACK_TO_LOGIN";
    String INTENT_CREATE_GROUP = "INTENT_CREATE_GROUP";
    String INTENT_OPEN_LIST_IN_GROUP = "INTENT_OPEN_LIST_IN_GROUP";
    String INTENT_SCAN_DEVICE = "INTENT_SCAN_DEVICE";
    String INTENT_ROLLCALL = "INTENT_ROLLCALL";
    String INTENT_ROLLCALL_RESULT = "INTENT_ROLLCALL_RESULT";
    String INTENT_SET_DEVICE_REMIND = "INTENT_SET_DEVICE_REMIND";
    String INTENT_WRITE_DATA_TO_DEVICE_ACTIVITY = "INTENT_WRITE_DATA_TO_DEVICE_ACTIVITY";
    String INTENT_WRITE_DATA_TO_DEVICE_SERVICE = "INTENT_WRITE_DATA_TO_DEVICE_SERVICE";

}
