package com.shawn.newrollcall.MainView.GroupList.action;

/**
 * Created by Shawn Wu on 2017/12/3.
 *
 */

public interface GroupListInfoType {

    String GET_GROUP_LIST_INFO = "GET_GROUP_LIST_INFO";
    String GET_GROUP_LIST_INFO_SUCCESS = "GET_GROUP_LIST_INFO_SUCCESS";
    String UPDATE_SELECT_IMAGE = "UPDATE_SELECT_IMAGE";
    String CREATE_GROUP = "CREATE_GROUP";
    String CREATE_GROUP_SUCCESS = "CREATE_GROUP_SUCCESS";
    String CREATE_GROUP_FAIL = "CREATE_GROUP_FAIL";
    String DELETE_GROUP = "DELETE_GROUP";
    String DELETE_GROUP_SUCCESS = "DELETE_GROUP_SUCCESS";
    String SETSELECTIMAGEPOSITIONZERO = "SETSELECTIMAGEPOSITIONZERO";
    String UPDATE_SELECT_GROUP = "UPDATE_SELECT_GROUP";
}
